version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true 
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_PASSWORD_RESET=true

  csv-server:
    image: nginx:alpine  # A lightweight, stable web server
    container_name: csv-server
    ports:
      - 8080:80  # Expose the server on host port 8080
    volumes:
      - ./data:/usr/share/nginx/html:ro
    restart: unless-stopped
