version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true 
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=volkovlabs-table-panel,yesoreyeram-infinity-datasource,marcusolsson-dynamictext-panel
      - GF_TIME_PICKER_QUICK_RANGES=[{"from":"now-6M","to":"now","display":"Last 6 months"},{"from":"now-1y","to":"now","display":"Last year"},{"from":"now-2y","to":"now","display":"Last 2 years"},{"from":"now-5y","to":"now","display":"Last 5 years"}]
      - GF_DATE_FORMATS_INTERVAL_MONTH=MMM-YYYY
      - GF_USERS_DEFAULT_THEME=light
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=grafana_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=metrics_db
    volumes:
      - ./pg_init_scripts:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/postgresql/import:ro

  filebrowser:
    image: gtstef/filebrowser:stable-slim
    container_name: filebrowser-quantum
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./data/upload:/srv:rw
    environment:
      - FILEBROWSER_ADMIN_PASSWORD=admin
      - FILEBROWSER_BASEURL=/

  file-processor:
    image: devodev/inotify
    container_name: file-upload-trigger
    entrypoint: /bin/sh /scripts/init.sh
    environment:
      - INOTIFY_TARGET=/data
      - INOTIFY_SCRIPT=/scripts/fileproc.sh
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=grafana_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=metrics_db
    volumes:
      - ./data:/grafana_target
      - ./data/upload:/data:rw
      - ./inotify_scripts:/scripts:ro
      - ./prepare_date.py:/prepare_date.py

