version: '3.8'
services:
  grafana:
    build: 
      context: ..
      dockerfile: docker_build/heart360.grafana.docker
  postgresql:
    build: 
      context: ..
      dockerfile: docker_build/heart360.pg_database.docker

  filebrowser:
    image: gtstef/filebrowser:stable-slim
    container_name: filebrowser-quantum
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./data/upload:/srv:rw
    environment:
      - FILEBROWSER_ADMIN_PASSWORD=admin
      - FILEBROWSER_BASEURL=/

  fileprocessor:
    image: devodev/inotify
    container_name: file-upload-trigger
    entrypoint: /bin/sh /scripts/init.sh
    environment:
      - INOTIFY_TARGET=/data
      - INOTIFY_SCRIPT=/scripts/fileproc.sh
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=grafana_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=metrics_db
    volumes:
      - ./data:/grafana_target
      - ./data/upload:/data:rw
      - ./inotify_scripts:/scripts:ro
      - ./prepare_date.py:/prepare_date.py

