version: '3.8'
services:
  grafana:
    build: 
      context: ..
      dockerfile: docker_build/heart360.grafana.docker
  postgresql:
    build: 
      context: ..
      dockerfile: docker_build/heart360.pg_database.docker
  fileprocessor:
    build: 
      context: ..
      dockerfile: docker_build/heart360.fileproc.docker